/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.65
 * Generated at: 2022-09-29 03:22:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class boardWrite_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width\" initial-scal=\"1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/bootstrap.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/board.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"css/layout.css\">\r\n");
      out.write("<title>BoardWrite.jsp</title>\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write(".back-btn a{\r\n");
      out.write("	color: #000;\r\n");
      out.write("	padding: 0.3em 3em 0.3em 3em;\r\n");
      out.write("	background: #f0f0f0;\r\n");
      out.write("	border: 1px solid #ccc;\r\n");
      out.write("	text-decoration: none;\r\n");
      out.write("}\r\n");
      out.write("footer {\r\n");
      out.write("	height: auto;\r\n");
      out.write("	background: none;\r\n");
      out.write("}\r\n");
      out.write(".ft-wrap {\r\n");
      out.write("	border-top: 1px solid #ccc;\r\n");
      out.write("	text-align: center;\r\n");
      out.write("	padding: 2em 0em 2em 0em;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("<script language=javascript>\r\n");
      out.write("function checkValid() {\r\n");
      out.write("    var f = window.document.writeForm;\r\n");
      out.write(" 	if ( f.select.value == \"\" ) {\r\n");
      out.write("		alert( \"분류를 선택해 주세요.\" );\r\n");
      out.write("		return false;\r\n");
      out.write("	} \r\n");
      out.write("	if ( f.title.value == \"\" ) {\r\n");
      out.write("		alert( \"제목을 입력해 주세요.\" );\r\n");
      out.write("		return false;\r\n");
      out.write("	}\r\n");
      out.write("    return true;\r\n");
      out.write("}\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("	\r\n");
      out.write("<!-- 네비게이션 -->\r\n");
      out.write("<nav class=\"navbar navbar-default\">\r\n");
      out.write("		<!-- 네비게이션 상단 Header  --> \r\n");
      out.write("		<div class=\"navnar-header\">\r\n");
      out.write("			<button \r\n");
      out.write("				type=\"button\"\r\n");
      out.write("				class=\"navbar-toggle collapese\"\r\n");
      out.write("				data-toggle=\"collapse\"\r\n");
      out.write("				data-target=\"#bs-example-navbar-collapse-1\"\r\n");
      out.write("				aria-expanded=\"false\">\r\n");
      out.write("				\r\n");
      out.write("				<span class=\"icon-bar\"></span>\r\n");
      out.write("				<span class=\"icon-bar\"></span>\r\n");
      out.write("				<span class=\"icon-bar\"></span>\r\n");
      out.write("			</button>\r\n");
      out.write("			<a class=\"navbar-brand\" href=\"board.do?command=backDrop\">\r\n");
      out.write("				PP 게시판 웹 사이트\r\n");
      out.write("			</a>			\r\n");
      out.write("		</div>\r\n");
      out.write("		\r\n");
      out.write("		<!-- 메뉴 영역 깃허브 링크 이동 -->\r\n");
      out.write("		<div class=\"collapse navbar-collapse\" id=\"bs-example-navbar-collapse-1\">\r\n");
      out.write("			<ul class=\"nav navbar-nav\">\r\n");
      out.write("				<li><a href=\"https://github.com/Bora0k\" target=\"_blacnk\">강보라</a></li>\r\n");
      out.write("				<li><a href=\"https://github.com/hyunminini\" target=\"_blacnk\">김현민</a></li>\r\n");
      out.write("				<li><a href=\"https://github.com/poviea\" target=\"_blacnk\">김민욱</a></li>\r\n");
      out.write("			</ul>		\r\n");
      out.write("		\r\n");
      out.write("			<!-- 메뉴 드랍다운 영역 -->\r\n");
      out.write("			<ul class=\"nav navbar-nav navbar-right\">\r\n");
      out.write("				<li class=\"dropdown\">\r\n");
      out.write("					<a href=\"#\"\r\n");
      out.write("						class=\"dropdown-toggle\"\r\n");
      out.write("						data-toggle=\"dropdown\"\r\n");
      out.write("						role=\"button\"\r\n");
      out.write("						aria-haspopup=\"true\"\r\n");
      out.write("						aria-expanded=\"false\"\r\n");
      out.write("					>\r\n");
      out.write("					사번  ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\r\n");
      out.write("	\r\n");
      out.write("					<span class=\"caret\"></span>\r\n");
      out.write("					</a>\r\n");
      out.write("				<!-- 드랍다운 아이템 영역 -->\r\n");
      out.write("				<ul class=\"dropdown-menu\">\r\n");
      out.write("					<li class=\"active\"> \r\n");
      out.write("						<a href=\"logoutAction.jsp\">로그아웃</a>\r\n");
      out.write("					</li>\r\n");
      out.write("				</ul>\r\n");
      out.write("			</li>\r\n");
      out.write("		</ul>\r\n");
      out.write("	</div>\r\n");
      out.write("</nav>\r\n");
      out.write("	\r\n");
      out.write("	<!-- 메인 이미지 -->\r\n");
      out.write("<div class=\"mainImg\"></div>\r\n");
      out.write("\r\n");
      out.write("<div class=\"form-wrap\">\r\n");
      out.write("<form name=\"writeForm\" method=\"post\" action=\"board.do\" onSubmit='checkValid()'>\r\n");
      out.write("	<input type=\"hidden\" name=\"command\" value=\"write\">\r\n");
      out.write("	<table align=\"center\" cellpadding=\"5\" cellspacing=\"2\" width=\"100%\" border=\"1\">\r\n");
      out.write("      	<div class=\"board-text-flex\">\r\n");
      out.write("      		<h3 class=\"board-name\">게시글 작성</h3>\r\n");
      out.write("      		<p class=\"back-btn\"><a href=\"javascript:history.back();\">뒤로가기</a></p>\r\n");
      out.write("      	</div>\r\n");
      out.write("    	<tr>\r\n");
      out.write("       	 	<td class=\"left-td\">\r\n");
      out.write("            	<p class=\"board-in-text\">분류</p>\r\n");
      out.write("        	</td>	\r\n");
      out.write("        	<td class=\"right-td\">\r\n");
      out.write("				<select class=\"category\" name=\"category\">\r\n");
      out.write("					<option value=\"자유게시판\">자유게시판</option>\r\n");
      out.write("					<option value=\"점메추\">점메추</option>\r\n");
      out.write("					<option value=\"유머\">유머</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			</td>\r\n");
      out.write("    	</tr>\r\n");
      out.write("    	<tr>\r\n");
      out.write("        	<td class=\"left-td\">\r\n");
      out.write("            	<p class=\"board-in-text\">제목</p>\r\n");
      out.write("       		</td>\r\n");
      out.write("        	<td class=\"right-td\">\r\n");
      out.write("				<input class=\"title\" type=text name=\"title\" placeholder=\"제목을 입력해주세요\">\r\n");
      out.write("			</td>\r\n");
      out.write("   		</tr>\r\n");
      out.write("    \r\n");
      out.write("   		<tr>\r\n");
      out.write("       		<td class=\"left-td\">\r\n");
      out.write("            	<p class=\"board-in-text\">내 용</p>\r\n");
      out.write("        	</td>\r\n");
      out.write("        	<td class=\"right-td\">\r\n");
      out.write("				<textarea name=\"content\" cols=\"50\" rows=\"10\"></textarea>\r\n");
      out.write("			</td>\r\n");
      out.write("    	</tr>\r\n");
      out.write("	</table>\r\n");
      out.write("	<input type=\"hidden\" name=\"board_cnum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${board_cnum}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></input>\r\n");
      out.write("	<input type=\"hidden\" name=\"empno\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${empno}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"></input>\r\n");
      out.write("\r\n");
      out.write("	<div class=\"btn-wrap\">\r\n");
      out.write("		<input class=\"submit\" type=\"submit\" value=\"게시글 작성\"> \r\n");
      out.write("	</div>\r\n");
      out.write("</form>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<footer>\r\n");
      out.write("	<div class=\"max-wrap\">\r\n");
      out.write("		<div class=\"ft-wrap\">\r\n");
      out.write("			<h3>PP_Project</h3>\r\n");
      out.write("			<p>Team: Bora0k, hyunminini, poviea</p>\r\n");
      out.write("			<p>©2022 Java Mini Project</p>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("</footer>\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://code.jquery.com/jquery-3.1.1.min.js\"></script>\r\n");
      out.write("<script src=\"js/bootstrap.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
